version: 2.0.{build}
image: Visual Studio 2017
configuration: Release
skip_tags: true
environment:
  deploy_token:
    secure: WGPN509P83WUoyHa9LJ+yXqS4zm8Ql1mOg9pzl3eUzg0JWEO+pjL1hJEHgclkUPR
deploy:
- provider: GitHub
  artifact: H2Codez.dll, hash, Release\*
  auth_token:
    secure: KEk0FetjPrWziRGWRW7YwQ==
  on:
    branch: H2OS_EK
- provider: FTP
  host: ftp.dlptest.com
  protocol: ftp
  username: dlpuser@dlptest.com
  password:
    secure: YMFg0qsprFpw24EX2gPxvQ==
  folder: /Tools/PC/h2codez/$(APPVEYOR_BUILD_VERSION)
  artifact: Release\H2Codez.dll, Release\H2Codez.pdb ,hash
  active_mode: false
  beta: true
  debug: true
  on:
    branch: H2OS_EK
before_build:
- cmd: 'echo #define version ^"%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT:~0,7%^" 1>  H2Codez\Version.h'
- cmd: 'cat H2Codez\Version.h'
build:
  verbosity: minimal
before_package:
- ps: Add-Content version $env:APPVEYOR_BUILD_VERSION -NoNewLine
- ps: Add-Content hash ((Get-FileHash "C:\Program Files (x86)\Microsoft Games\Halo 2 Map Editor\H2Codez.dll" -Algorithm MD5).Hash) -NoNewLine
- cmd: xcopy /i "C:\Program Files (x86)\Microsoft Games\Halo 2 Map Editor\H2Codez.dll" ".\Release\"
- cmd: xcopy /i "C:\Program Files (x86)\Microsoft Games\Halo 2 Map Editor\H2Codez.pdb" ".\Release\"
artifacts:
- path: '\Release\*'
- path: '\version'
- path: '\Patches\*'
- path: '\hash'